name: Build & Deploy Flask App using EC2  SSH

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Runs inside your EC2 instance

    steps:
    - name:  Checkout code
      uses: actions/checkout@v3

    - name:  Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name:  Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/apssdc-flask-app:latest .

    - name:  Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/apssdc-flask-app:latest


    - name:  Deploy on remote EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_SERVER_HOST }}
        username: ${{ secrets.PROD_SERVER_USER }}
        key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
        script: |
          docker stop apssdc-container || true
          docker rm apssdc-container || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/apssdc-flask-app:latest
          docker run -d --name apssdc-container -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/apssdc-flask-app:latest
