name: Deploy Flask App on EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name:  Checkout code
      uses: actions/checkout@v3

    - name:  Build Docker image
      run: docker build -t apssdc-flask-app .

    - name:  Run container
      run: |
        docker stop apssdc-container || true
        docker rm apssdc-container || true
        docker run -d --name apssdc-container -p 5000:5000 apssdc-flask-app
