name: Build & Deploy Flask App using EC2 Self-Hosted Runner

on:
  push:
    branches: [ main ]  # Trigger only when code is pushed to main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted  # This makes GitHub Actions use your EC2 instance

    steps:
    - name:  Checkout code
      uses: actions/checkout@v3

    - name:  Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name:  Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/apssdc-flask-app:latest .

    - name:  Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/apssdc-flask-app:latest

    - name:  Deploy Container on EC2 (Self-hosted)
      run: |
        docker stop apssdc-container || true
        docker rm apssdc-container || true
        docker pull ${{ secrets.DOCKER_USERNAME }}/apssdc-flask-app:latest
        docker run -d --name apssdc-container -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/apssdc-flask-app:latest
